FROM --platform=linux/amd64 ubuntu:20.04 as builder
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y bmake gcc

COPY . /libfsm
WORKDIR /libfsm
RUN bmake -r

FROM ubuntu:20.04 as package
COPY --from=builder /libfsm/build/bin/fsm /
